FROM golang:1.16.11-bullseye

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y dnsutils git libsnappy-dev liblz4-dev libzstd-dev zlib1g-dev
RUN git clone https://github.com/facebook/rocksdb.git && \
    cd rocksdb && \
    git checkout v6.26.1 && \
    make shared_lib && \
    make install-shared

CMD ["bash"]
